### ISSUE TITLE
Feature request. on GPU and multipose.

### ISSUE THREAD

**Issue by aafaqin** [geaxgx/openvino_movenet_multipose#1]
Hey can you please add GPU based inference. 
Also, can OpenVino run just as well on AMD? 
Is inference faster with openVino or the tensorflow's method?

**Comment by geaxgx** [comment]
Hi,
As far as I know, OpenVino is only supported on Intel processors. Here is the list: https://docs.openvinotoolkit.org/2021.4/openvino_docs_IE_DG_supported_plugins_Supported_Devices.html

In this repo, I am using the work of PINTO who did the conversion of the model from tensorflow to OpenVino: https://github.com/PINTO0309/PINTO_model_zoo/tree/main/137_MoveNet_MultiPose
Currently, the converted model is only working on CPU, but not working on iGPU nor MyriadX. 

* If I try to run it on my Intel iGPU, I get the following error message:
```
RuntimeError: Error has occured for: floor:floordiv_StatefulPartitionedCall/floordiv
Requested activation is not supported for integer type.
```
There is a method to get around this error but it implies a manual modification of the xml file. I don't have applied this fix on Movenet Multipose yet but have on Movenet Single Pose V4 which generates a similar error. Unfortunately, I encountered another problem after the fix. So I feel a bit pessimistic on making it work on the GPU.

* On MyriadX,  It seems there is bug with the compiler that converts from OpenVino IR to blob format. PINTO has open an issue with Intel support.

I will let you know here if we were able to make progress.

About the inference speed comparison, I can't say as I haven't tested the tensorflow method.

**Comment by lsprior** [comment]
Hello,
Any news on using this model on myriadx?
 I tried to convert this model using the openvino mo tool without success. It gives the same error as you point out above, but seeing that more than a year has passed since the last comment,  maybe you know some tricks now to make it work.

Regards

**Comment by geaxgx** [comment]
@lsprior No positive news, sorry.
